name: "✨ Feature Request"
description: "Suggest a new feature or improvement for an iHost add-on."
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: input
    id: addon_name
    attributes:
      label: "Add-on Name"
      description: "Which add-on is this request for?"
      placeholder: "eWeLink-Remote Gateway"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Request Description"
      description: |
        Describe the feature and the problem it solves.
        Please include why this feature is useful and in which scenario it will be used.
      placeholder: |
        What problem does this feature solve?
        Who would benefit from it?
        How should it work?
    validations:
      required: true
