name: "✨ Feature Request"
description: "Suggest a new feature or improvement for an iHost add-on."
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: dropdown
    id: addon_name
    attributes:
      label: "Add-on Name"
      description: "Which add-on is affected?"
      options:
        - "-- Please select an add-on --"
        - "eWeLink Smart Home"
        - "eWeLink-Remote Gateway"
        - "SONOFF Dongle Flasher"
        - "iHost Hardware Control"
        - "Matter Bridge for iHost"
        - "Silicon Labs Multiprotocol"
        - "OpenThread Border Router"
        - "Node-RED"
        - "ESPHome Device Builder"
        - "Matter Server"
        - "Advanced SSH & Web Terminal"
        - "Zigbee2MQTT"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Request Description"
      description: |
        Describe the feature and the problem it solves.
        Please include why this feature is useful and in which scenario it will be used.
      placeholder: |
        What problem does this feature solve?
        Who would benefit from it?
        How should it work?
    validations:
      required: true
