---
version: 1.0.0
slug: hassio_ihost_silabs_multiprotocol
name: Silicon Labs Multiprotocol
description: Zigbee and OpenThread multiprotocol add-on
url: >
  https://github.com/iHost-Open-Source-Project/hassio-ihost-addon/tree/master/hassio-ihost-silabs-multiprotocol
arch:
  - armv7
  - aarch64
  - amd64
homeassistant: 2024.1.0
gpio: true
hassio_api: true
discovery:
  - otbr
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_uts: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
image: ghcr.io/ihost-open-source-project/hassio-ihost-silabs-multiprotocol-{arch}
init: false
options:
  device: null
  baudrate: "115200"
  flow_control: false
  cpcd_trace: false
  otbr_enable: true
  otbr_log_level: notice
  otbr_firewall: true
ports:
  9999/tcp: null
  8080/tcp: null
  8081/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
  8080/tcp: OpenThread Web port
  8081/tcp: OpenThread REST API port
schema:
  device: device(subsystem=tty)?
  baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  network_device: str?
  cpcd_trace: bool
  otbr_enable: bool
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  otbr_firewall: bool
stage: stable
startup: services
