name: Check Release
inputs:
  owner:
    description: "Owner"
    required: true
    example: "esphome"
  repo:
    description: "Repo"
    required: true
    example: "home-assistant-addon"
runs:
  using: "composite"
  steps:
    - name: Get current release
      id: get
      shell: bash
      run: |
        response=$(curl -s -w "%{http_code}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/releases/latest")
        
        http_code="${response: -3}"
        response_body="${response%???}"

        if [ "$http_code" -ne 200 ]; then
          echo "Failed to fetch release data. HTTP status: $http_code"
          exit 1
        fi

        current_version=$(echo "$response_body" | jq -r '.tag_name')
        release_url=$(echo "$response_body" | jq -r '.html_url')
        body="[CHANGELOG.md](https://github.com/${{ inputs.owner }}/${{ inputs.repo }}/releases/tag/$current_version)"

        echo "current_version<<EOF" >> $GITHUB_OUTPUT
        echo "$current_version" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "release_url<<EOF" >> $GITHUB_OUTPUT
        echo "$release_url" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "Current release: $current_version"
        echo "Release url: $release_url"
        echo "Body: $body"

    - name: Compare with previous release
      if: steps.get.outputs.current_version != null && steps.get.outputs.current_version != ''
      id: compare
      uses: ./.github/actions/compare-with-previous
      with:
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        current_version: ${{ steps.get.outputs.current_version }}
        release_url: ${{ steps.get.outputs.release_url }}
        body: ${{ steps.get.outputs.body }}
